version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    links:
      - db:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.development
    networks:
      - db

# Review networks and volumes
networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local